version: '3'
services:
  wapp:
    build: .
    depends_on:
      - redis
    links:
      - redis
    ports:
      - '3000:3000'

  redis:
    image: redis:4.0.6
    volumes:
      - redis_data:/var/lib/redis/data

  nginx:
    build:
      context: .
      dockerfile: Nginxfile
    ports:
      - '80:80'
    links:
      - wapp

volumes:
  redis_data:
