source 'https://gems.ruby-china.org'
gem 'rake'
gem 'sinatra'
gem 'rack', '<2.0'
# gem 'puma'
gem 'sinatra-flash'
gem 'json'
gem 'redis'
gem 'hiredis'
gem 'slim'
gem 'qiniu'
gem 'unicorn'
gem 'activesupport'
gem 'bcrypt'
gem 'task'
gem 'sass'
# gem 'sinatra-assetpack', :require => 'sinatra/assetpack'

group :development do
  gem 'rerun'
  gem 'pry'
  gem 'mina'
end
