source 'https://ruby.taobao.org/'
gem 'sinatra'
gem 'sinatra-flash'
gem 'json'
gem 'redis'
gem 'hiredis'
gem 'slim'
gem 'qiniu'
gem 'unicorn'
gem 'activesupport'
gem 'bcrypt'
gem 'task'
group :development do
  gem 'rerun'
  gem 'pry'
end
